# Publish GitHub workflow artifacts tutorial example
name: Upload & Download Artifacts Example

on:
  workflow_dispatch:

jobs:
       
  upload-sample-artifacts:
    runs-on: ubuntu-latest
    steps:

      - name: Step 1 - Create a temporary artifact downloads folder
        run: mkdir downloads
        
      - name: step 2 - Add artifacts to publish to the temp folder
        run: |
          cd downloads
          echo 'alpha'    > alpha.html
          echo 'bravo'    > bravo.html
          echo 'charlie'  > charlie.html
          cd ..
    
      - name: Step 3 - Use the Upload Artifact GitHub Action
        uses: actions/upload-artifact@v3
        with: 
          name: assets-for-download
          path: downloads

  download-sample-artifacts:
    needs: upload-sample-artifacts
    runs-on: ubuntu-latest
    steps:

      - name: Let us download artifact named assets-for-download
        uses: actions/download-artifact@v3
        with:
          name: assets-for-download

      - name: List out folders & files in the present directory
        shell: bash
        run: | 
          pwd
          ls
